server:
  port: 8888
  http2:
    enabled: true
  shutdown: graceful
  forward-headers-strategy: native

spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s
  profiles:
    active: @profile.env@
  servlet:
    multipart:
      max-request-size: 64MB
      max-file-size: 16MB
  output:
    ansi:
      enabled: always

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-handlers-package: com.ynthm.demo.mybatis.common.handler
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: false
      logic-delete-value: true
    banner: false
  type-enums-package: com.ynthm.demo.mybatis.enums