server:
  port: 9002
spring:
  application:
    name: user
  cloud:
    openfeign:
      okhttp:
        enabled: true
      httpclient:
        disable-ssl-validation: true

logging:
  level:
    com.ynthm.cloud.user.client: debug